apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kluster-cr
rules:
- apiGroups:
  - viveksingh.dev
  resources:
  - klusters
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  verbs:
  - create
  - get
- apiGroups:
  - viveksingh.dev
  resources:
  - klusters/status
  verbs:
  - update
- apiGroups:
  - viveksingh.dev
  resources:
  - klusters
  verbs:
  - get
  - update
